cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED CLI_EXE)
    message(FATAL_ERROR "DeployLatestInstalledCli.cmake requires -DCLI_EXE")
endif()
if(NOT EXISTS "${CLI_EXE}")
    message(FATAL_ERROR "Built MipsyncCLI executable not found: ${CLI_EXE}")
endif()
if(NOT DEFINED ENV{APPDATA} OR "$ENV{APPDATA}" STREQUAL "")
    message(STATUS "APPDATA is unavailable; skipping installed CLI deployment")
    return()
endif()

file(TO_CMAKE_PATH "$ENV{APPDATA}/MipsyncEngine/Installs" _installs_root)
if(NOT IS_DIRECTORY "${_installs_root}")
    message(STATUS "No Mipsync installs directory found; skipping installed CLI deployment")
    return()
endif()

file(GLOB _candidates LIST_DIRECTORIES true "${_installs_root}/v*")
set(_versions)
foreach(_candidate IN LISTS _candidates)
    if(IS_DIRECTORY "${_candidate}")
        get_filename_component(_name "${_candidate}" NAME)
        if(_name MATCHES "^v[0-9]+(\\.[0-9]+)*$")
            list(APPEND _versions "${_candidate}")
        endif()
    endif()
endforeach()
if(NOT _versions)
    message(STATUS "No versioned Mipsync install found; skipping installed CLI deployment")
    return()
endif()

list(SORT _versions COMPARE NATURAL ORDER DESCENDING)
list(GET _versions 0 _latest)
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${CLI_EXE}" "${_latest}/mipsync.exe"
    RESULT_VARIABLE _copy_result
)
if(NOT _copy_result EQUAL 0)
    message(FATAL_ERROR "Failed to deploy mipsync.exe to ${_latest}")
endif()
message(STATUS "Deployed MipsyncCLI to latest install: ${_latest}")
